Remade quad renderer class with etna
msu-graphics-group/vk_graphics_basic pull request #45
Opened 2024-01-29 21:21 UTC by JackOfBlades232

Remade the QuadRenderer class to etna from vk_utils, which allows us to draw any 2d texture to a part of the screen. I also reimplemented debug drawing of the lightmap in shadowmap_renderer to use this class.

This class uses the full power of etna's context, thus removing the need to keep track of it's descriptor sets, and allows for all draw commands to be issued in one method call. 

The usage of the class is as follows: construct it with the coordinates and dimensions of the part of the screen you will be drawing to, use Create method to pass v/f shaders and create pipeline, and DrawCmd to issue draw commands to a given command buffer.

2024-01-29 21:31 UTC, Mrkol requested changes

2024-01-29 21:31 UTC, Mrkol commented on src/render/quad_renderer.cpp
> +void QuadRenderer::Create(const char *vspath, const char *fspath, CreateInfo info)
Не вижу смысла выносить это в отдельный метод, давай в конструктор запихаем.

2024-01-29 21:31 UTC, Mrkol commented on src/render/quad_renderer.cpp
> +void QuadRenderer::DrawCmd(VkCommandBuffer cmdBuff, VkImage targetImage, VkImageView targetImageView,
draw cmd -> render 
renderer должен уметь делать действие render

2024-01-29 21:31 UTC, Mrkol commented on src/render/quad_renderer.h
> +  };
вот сюда же запихнуть и rect на размер, и всё это в конструктор

2024-01-29 21:31 UTC, Mrkol commented on src/samples/shadowmap/shadowmap_render.cpp
> +    { .format = (vk::Format)m_swapchain.GetFormat() }
сишные касты зло, сделай явным каст который тут происходит

2024-01-29 21:31 UTC, Mrkol commented on src/samples/shadowmap/shadowmap_render.cpp
> +  m_pQuad = std::make_shared<QuadRenderer>(0,0, 512, 512);
замени за одно тут shared на unique

2024-01-29 21:31 UTC, Mrkol commented on src/samples/shadowmap/shadowmap_render.cpp
> +  m_pQuad = nullptr; // smartptr delete it's resources
комментарий бесполезный кстати, убери его тоже пж

2024-01-30 16:16 UTC, JackOfBlades232 commented on src/render/quad_renderer.cpp
> +void QuadRenderer::DrawCmd(VkCommandBuffer cmdBuff, VkImage targetImage, VkImageView targetImageView,
#То есть он должен уметь сам без чьей либо помощи рендериться (т е иметь свой буффер и запускать universalQueue контекста), или просто переименовать? Просто сменить имя получается не совсем честно по отношению к тому, что он сейчас делает.

> draw cmd -> render renderer должен уметь делать действие render

2024-01-30 19:39 UTC, JackOfBlades232 commented on src/samples/shadowmap/shadowmap_render.cpp
> +    { .format = (vk::Format)m_swapchain.GetFormat() }
По моему скромному мнению сишные касты кайф, и все остальное -- не(всегда)обязательные заморочки, но я понимаю смысл, сделаю)

2024-01-30 22:01 UTC, Mrkol commented on src/samples/shadowmap/shadowmap_render.cpp
>      VK_GRAPHICS_BASIC_ROOT "/resources/shaders/quad3_vert.vert.spv",
Так,  а в чём вообще смысл сюда пихать какой-то другой фрагментный шейдер, если этот класс это буквально "quad renderer"? Мне кажется захардкодить вершинный шейдер надо

2024-02-05 21:16 UTC, Mrkol approved these changes

2024-02-05 21:16 UTC, merged